config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  devise_for :users
  resources :users, only: [:show]
  resources :comments
  resources :likes, only: [:new, :create, :destroy]

  delete '/likes/',            to: 'likes#destroy'
  get    '/likes/',            to: 'likes#get_likers'
  delete '/follow/',           to: 'user_followers#destroy'
  post   '/follow/',           to: 'user_followers#create'
  get    '/friends/',          to: 'user_followers#index'
  get    '/share/:id',         to: 'posts#share', :as => :share_post
  delete '/followRequest/',    to: 'follow_requests#destroy'
  post   '/followRequest/',    to: 'follow_requests#create'
  get    '/followRequests/',   to: 'follow_requests#index', :as => :follow_requests
  get    '/userspdf/:id',      to: 'users#create_pdf', :as => :create_pdf

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true
  
  has_many :posts, dependent: :destroy       
  has_many :comments, dependent: :destroy       
  has_many :likes, dependent: :destroy       
  # follower_follows "names" the Follow join table for accessing through the follower association
  has_many :follower_follows, foreign_key: :followee_id, class_name: "UserFollower" 
  # source: :follower matches with the belong_to :follower identification in the Follow model 
  has_many :followers, through: :follower_follows, source: :follower

  # followee_follows "names" the Follow join table for accessing through the followee association
  has_many :followee_follows, foreign_key: :follower_id, class_name: "UserFollower"    
  # source: :followee matches with the belong_to :followee identification in the Follow model   
  has_many :followees, through: :followee_follows, source: :followee


  has_many :follower_request_relation, foreign_key: :request_follower_id, class_name: "FollowRequest" 
  has_many :follower_requests, through: :follower_request_relation, source: :request_follower , dependent: :destroy
 
  has_many :followee_request_relation, foreign_key: :request_followee_id, class_name: "FollowRequest" 
  has_many :followee_requests, through: :followee_request_relation, source: :request_followee , dependent: :destroy
 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 	
 	before_action :set_user , only: [:show , :create_pdf]	
 	before_action :require_login

	def show
		# CHANGE
	
		if current_user.id != @user.id

			@is_follower = UserFollower.find_by(followee_id: @user.id, follower_id: current_user.id)? true : false
			@is_requester = FollowRequest.find_by(request_follower_id: current_user.id, request_followee_id: @user.id)? true : false
			puts "---------------------------------------------#{@is_requester}"
			if @is_follower
				@posts = Post.where("user_id = (?) ", @user.id).order(created_at: :desc)
			else
				@posts = Post.where("user_id = (?) AND privacy = (?)", @user.id , Post.privacies["public_post"]) 
							 .order(created_at: :desc)
			end 
		
		else
			@posts = Post.where("user_id = (?) ",@user.id).order(created_at: :desc)
			
		end	
	
	end	
	
	def create_pdf		 
		
		@posts = Post.where("user_id = (?) ",@user.id).order(created_at: :desc)
	
		html = render_to_string(:action => "show.html.erb" , :layout => false)
		kit = PDFKit.new(html)
		kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/custom.css.scss"
		kit.to_file("public/pdfs/hello.pdf")
		# send_data(kit.to_pdf, :filename => 'report.pdf', :type =>
		render :nothing => true	
	end



	private
	 # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

	 # # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id)
    end


	def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_session_path
      end
 	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%content_for :javascripts do %>
   <%= javascript_include_tag 'posts' %>
<% end %>

<h1> 
 	<strong> <%= @user.username %>'s Profile </strong> 
</h1> 

<div>
  <%= link_to "PDF", create_pdf_path, class: "btn btn-xs btn-primary" %>
</div>

<% if  @user.id != current_user.id %>

	<div class = "visitor-profile-actions">

		<%if @is_follower %>

		    <button id="unfollow-btn" data-profile-id="<%= @user.id %>" data-status="unfollow"
                              class="follow-btn btn btn-xs btn-primary" >unfollow</button>  
        
        <button id="follow-btn" data-profile-id="<%= @user.id %>" data-status="follow"  
			                        class="follow-btn btn btn-xs btn-primary" style="display: none" >Folllow</button>

    <%elsif @is_requester %>

      <button id="request-follow-btn" data-profile-id="<%= @user.id %>" data-status="request"  
                                      class="follow-btn btn btn-xs btn-primary" >cancel follow request</button>

      <button id="follow-btn" data-profile-id="<%= @user.id %>" data-status="follow"  
                              class="follow-btn btn btn-xs btn-primary" style="display: none" >Folllow</button>

		
    <% else %>

			<button id="follow-btn" data-profile-id="<%= @user.id %>" data-status="follow"  
			                        class="follow-btn btn btn-xs btn-primary"  >Folllow</button>

      <button id="request-follow-btn" data-profile-id="<%= @user.id %>" data-status="request"  
                                class="follow-btn btn btn-xs btn-primary" style="display: none" >cancel follow request</button>

		<% end %>

	</div>

<% end %> 
	


<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 ">  
      <div class="well well-lg">  
         
          <div class="post-owner">
            <%= link_to post.user.username , user_path(post.user.id) %>
          </div>

          <div class="post-title">
            <%= link_to post.title, post_path(post) %>
          </div>

          <div>
            <%= raw post.body %>
          </div>

        <% if post.parent_post_id %>
          
          <div class="row">
            <div class="col-xs-8  ">  
              <div class="well well-lg">  
                
                <% parent_post = post.parent_post %>

                <div class="post-owner">
                  <%= link_to parent_post.user.username , user_path(parent_post.user.id) %>
                </div>

                <div class="post-title">
                  <%= link_to parent_post.title, post_path(parent_post) %>
                </div>

                <div>
                  <%= raw parent_post.body %>
                </div> 
              </div>   
            </div>
          </div>
        <% end %>
        


        <%if post.user == current_user %>
        
          <div class="owner-post-actions">
            <%= link_to 'Edit', edit_post_path(post) , class: "btn btn-xs btn-primary" %> 
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' },
            class: "btn btn-xs btn-primary"%>           
          </div>

        <%end%>

        <div class="user-post-actions">
          
          <p class="show-likes-btn" data-post-id="<%= post.id %>"> <%="#{post.likes_num} likes"%></p>
        
           <%unless post.likers.include? current_user %>

              <button id="like-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="like"  
                                  class="like-btn btn btn-xs btn-primary" >like</button>

              <button id="unlike-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="unlike"
                                  class="like-btn btn btn-xs btn-primary" style="display: none" >unlike</button>  
            
          <%else%>

              <button id="like-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="like"  
                                  class="like-btn btn btn-xs btn-primary" style="display: none" >like</button>

              <button id="unlike-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="unlike"
                                  class="like-btn btn btn-xs btn-primary"  >unlike</button>

          <%end%>

          <% if (post.privacy ==  "public_post") || (post.user == current_user ) %>         
              <%= link_to 'Share', share_post_path(post) , class: "btn btn-xs btn-primary" %> 
          <% end %>


        </div>

      
      </div>   
    </div>
  </div>
<%end%>     
    