config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  devise_for :users
  resources :users, only: [:show]
  resources :comments
  resources :likes, only: [:new, :create, :destroy]

  delete '/likes/',            to: 'likes#destroy'
  get    '/likes/',            to: 'likes#get_likers'
  delete '/follow/',           to: 'user_followers#destroy'
  post   '/follow/',           to: 'user_followers#create'
  get    '/friends/',          to: 'user_followers#index'
  get    '/share/:id',         to: 'posts#share', :as => :share_post
  delete '/followRequest/',    to: 'follow_requests#destroy'
  post   '/followRequest/',    to: 'follow_requests#create'
  get    '/followRequests/',   to: 'follow_requests#index', :as => :follow_requests
  get    '/userspdf/:id',      to: 'users#create_pdf', :as => :create_pdf

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	validates :title, :user, :body, presence: true

	has_many :comments, dependent: :destroy       
	has_many :likes, 	dependent: :destroy 
	has_many :likers , through:  :likes ,  source: :user
	has_many :tags, 	dependent: :destroy 
	has_many :users , through:  :tags 	
	belongs_to  :parent_post , class_name: "Post"
	
	enum privacy: {private_post: 1, public_post: 2}

	accepts_nested_attributes_for :tags
	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  before_action :require_post_owner, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index

    @posts = Post.where("user_id in (?) OR user_id = (?) OR privacy = (?)", 
                        current_user.followee_ids, current_user.id , Post.privacies["public_post"])
                        .order(created_at: :desc)

    @my_friends = current_user.followees.ids
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new
    @comment.post_id = @post.id
    @already_liked = Like.find_by(post_id: @post.id, user_id: current_user.id)? true : false
    @is_shared = @post.parent_post_id? 

    if @is_shared
      @perant_post = Post.find(@post.parent_post_id)
    end

  end

  def share
    @parent_post = Post.find(params[:id])
    @my_friends = current_user.followees
    @post = Post.new
  end

  # GET /posts/new
  def new
    @post = Post.new    
    @my_friends = current_user.followees

  end

  # GET /posts/1/edit
  def edit
    
     @is_edit = true

  end

  # POST /posts
  # POST /posts.json
  def create
    
    @my_friends = current_user.followees
    
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new 
    end

  end

  # PATCH/PUT /posts/1
  def update

      old_ids = @post.tags.map(&:user_id)
      new_ids = post_params[:user_ids]
      new_ids.shift

      @post.user_ids = new_ids


      if @post.update(post_params)
        redirect_to @post ,  notice: 'Post was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /posts/1
  def destroy
    
    if @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.' 
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @my_friends = current_user.followees

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body , :privacy, :parent_post_id, user_ids: [])

    end

    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_session_path
      end
    end

    def require_post_owner
      if current_user != @post.user
        flash[:danger] = 'you can only do that for your own posts !'
        redirect_to root_path
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body %>
  </div>
  
  <div>
    <%= f.select :privacy, [['private','private_post'],['public','public_post']]  , :selected => @post.privacy %>
  </div>

  <% if @is_edit %>    
    <%= f.select :user_ids , options_from_collection_for_select(@my_friends, "id", "username", @post.tags.map(&:user_id)),{}, { :multiple => true, :size => 5}%>  
  <% else %>
    <div>
      <%= f.label :select_friends_to_tag %><br>
      <%= f.select :user_ids , options_from_collection_for_select(@my_friends, "id", "username"),{}, { :multiple => true, :size => 5} %>  
    </div>
  <% end %>
  
  
  <div class="actions" >
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
  $("#post_user_ids").select2({
        placeholder: "Choose a person",
        allowClear: true,
        multiple: true
  });

</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>


<% if @post.errors.any? %>	
	<ul>
	<% @post.errors.full_messages.each do |msg|%>
		<li><%= msg %></li>
	<%end%>
	</ul>
<%end%>


<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%content_for :javascripts do %>
   <%= javascript_include_tag 'posts' %>
<% end %>


<h1>Listing Posts</h1>
   
<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 ">  
      <div class="well well-lg">  
         
          <div class="post-owner">
            <%= link_to post.user.username , user_path(post.user.id) %>
          </div>

          <div class="post-title">
            <%= link_to post.title, post_path(post) %>
          </div>

          <div>
            <%= raw post.body %>
          </div>

        <% if post.parent_post_id %>
          
          <div class="row">
            <div class="col-xs-8  ">  
              <div class="well well-lg">  
                
                <% parent_post = post.parent_post %>

                <div class="post-owner">
                  <%= link_to parent_post.user.username , user_path(parent_post.user.id) %>
                </div>

                <div class="post-title">
                  <%= link_to parent_post.title, post_path(parent_post) %>
                </div>

                <div>
                  <%= raw parent_post.body %>
                </div> 
              </div>   
            </div>
          </div>
        <% end %>
        


        <%if post.user == current_user %>
        
          <div class="owner-post-actions">
            <%= link_to 'Edit', edit_post_path(post) , class: "btn btn-xs btn-primary" %> 
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' },
            class: "btn btn-xs btn-primary"%>
            <%= link_to 'Share', share_post_path(post) , class: "btn btn-xs btn-primary" %> 
           
          </div>

        <%end%>

        <div class="user-post-actions">
          
          <p class="show-likes-btn" data-post-id="<%= post.id %>"> <%="#{post.likes_num} likes"%></p>
        
           <%unless post.likers.include? current_user %>

              <button id="like-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="like"  
                                  class="like-btn btn btn-xs btn-primary" >like</button>

              <button id="unlike-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="unlike"
                                  class="like-btn btn btn-xs btn-primary" style="display: none" >unlike</button>  
            
          <%else%>

              <button id="like-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="like"  
                                  class="like-btn btn btn-xs btn-primary" style="display: none" >like</button>

              <button id="unlike-btn-<%= post.id %>" data-post-id="<%= post.id %>" data-status="unlike"
                                  class="like-btn btn btn-xs btn-primary"  >unlike</button>

          <%end%>

          <% if (post.privacy ==  "public_post") && (@my_friends.include? post.user_id) %>         
              <%= link_to 'Share', share_post_path(post) , class: "btn btn-xs btn-primary" %> 
          <% end %>


        </div>

      
      </div>   
    </div>
  </div>
<%end%>     

app/views/posts/new.html.erb
<h1>New Post</h1>


<% if @post.errors.any? %>	
  <ul>
	<% @post.errors.full_messages.each do |msg|%>
	  <li><%= msg %></li>
	<%end%>
  </ul>
<%end%>


<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/share.html.erb
<h1>Share Post</h1>


<% if @post.errors.any? %>	
	<ul>
	<% @post.errors.full_messages.each do |msg|%>
		<li><%= msg %></li>
	<%end%>
	</ul>
<%end%>

<div class="row">
    <div class="col-xs-8 ">  
      <div class="well well-lg">  

        <div class="post-owner">
          <h4><strong> <%= link_to @parent_post.user.username, user_path(@parent_post.user) %> </strong> </h4>
        </div>

        <div class="post-title">
          <h4><strong><%= @parent_post.title %></strong></h4>
        </div>

        <div>
          <%= raw @parent_post.body %>
        </div>

      </div>   
  </div>
</div>

<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  
  <div>
    <%= f.label :select_friends_to_tag %><br>
    <%= f.select :user_ids , options_from_collection_for_select(@my_friends, "id", "username"),{}, { :multiple => true, :size => 5} %>  
  </div>

  <div>
    <%= f.select :privacy, [['private','private_post'],['public','public_post']]  , :selected => @post.privacy %>
    
    <%= f.hidden_field :parent_post_id, {:value => @parent_post.id} %>  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%content_for :javascripts do %>
   <%= javascript_include_tag 'posts' %>
<% end %>


<% if @post.errors.any? %>	
  <ul>
	<% @post.errors.full_messages.each do |msg|%>
		<li><%= msg %></li>
	<%end%>
  </ul>
<%end%>

<% if @is_shared %>

  <div class="row">
      <div class="col-xs-6 ">  
        <div class="well well-lg">  

          <div class="post-owner">
            <h1><strong> <%= link_to @post.user.username, user_path(@post.user) %> </strong> </h1>
          </div>

          <div class="post-title">
            <h3><strong><%= @post.title %></strong></h3>
          </div>

          <div>
            <%= raw @post.body %>
          </div>

          <div class="row">
            <div class="col-xs-8 ">  
              <div class="well well-lg">  
                <div class="parent-post-owner">
                  <h3> <%= link_to @perant_post.user.username, user_path(@perant_post.user) %> </h3>
                  </div>

                  <div class="parent-post-title">
                    <h4><strong><%= @perant_post.title %></strong></h4>
                  </div>

                  <div>
                    <%= raw @perant_post.body %>
                  </div>                  

              </div>   
            </div>
          </div>


        </div>   
    </div>
  </div>

<% else %>

  <div class="row">
      <div class="col-xs-8 ">  
        <div class="well well-lg">  

          <div class="post-owner">
            <h3><strong> <%= link_to @post.user.username, user_path(@post.user) %> </strong> </h3>
          </div>

          <div class="post-title">
            <h4><strong><%= @post.title %></strong></h4>
          </div>

          <div>
            <%= raw @post.body %>
          </div>

        </div>   
    </div>
  </div>
  
<% end %>




<%if @post.user == current_user %>
  <div class = "owner-post-actions">
  <%= link_to 'Edit post', edit_post_path(@post) , class: "btn btn-xs btn-primary" %>
  <%= link_to 'Delete post', @post, method: :delete, data: {confirm: 'Are you sure you want to Delete the post ?'}  ,class: "btn btn-xs btn-danger" %>
  </div>
<%end%>

<div>

<div >    
    <p class="show-likes-btn" data-post-id="<%= @post.id %>"> <%="#{@post.likes_num} likes"%></p>
</div>

 <%unless @already_liked %>
  <div class = "user-post-actions">

    <button id="like-btn-<%= @post.id %>" data-post-id="<%= @post.id %>" data-status="like"  
                        class="like-btn btn btn-xs btn-primary" >like</button>

    <button id="unlike-btn-<%= @post.id %>" data-post-id="<%= @post.id %>" data-status="unlike"
                        class="like-btn btn btn-xs btn-primary" style="display: none" >unlike</button>

  
  </div>
  
<%else%>

  <div class = "user-post-actions">
    <button id="like-btn-<%= @post.id %>" data-post-id="<%= @post.id %>" data-status="like"  
                        class="like-btn btn btn-xs btn-primary" style="display: none" >like</button>

    <button id="unlike-btn-<%= @post.id %>" data-post-id="<%= @post.id %>" data-status="unlike"
                        class="like-btn btn btn-xs btn-primary"  >unlike</button>
  </div>

<%end%>


<% @comments.each do |com| %>
  <%= render :partial => 'comments/comment_show', :locals => {:comment => com} %>
<%end%>    

<p> 
  <%= render :partial => 'comments/comment_new', :locals => {:comment => @comment} %>
</p>