config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  devise_for :users
  resources :users, only: [:show]
  resources :comments
  resources :likes, only: [:new, :create, :destroy]

  delete '/likes/',            to: 'likes#destroy'
  get    '/likes/',            to: 'likes#get_likers'
  delete '/follow/',           to: 'user_followers#destroy'
  post   '/follow/',           to: 'user_followers#create'
  get    '/friends/',          to: 'user_followers#index'
  get    '/share/:id',         to: 'posts#share', :as => :share_post
  delete '/followRequest/',    to: 'follow_requests#destroy'
  post   '/followRequest/',    to: 'follow_requests#create'
  get    '/followRequests/',   to: 'follow_requests#index', :as => :follow_requests
  get    '/userspdf/:id',      to: 'users#create_pdf', :as => :create_pdf

  root 'welcome#index'

end

app/views/layouts/_alerts.html.erb
<!-- ASK how to remove these two lines ? -->

<!-- <p class="notice alert"><%= notice %></p>
<p class=""><%= alert %></p>
 -->
<% flash.each do |name ,msg| %>
	<ul>
		<li><%= msg  %></li>
	</ul>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TheBlog</a>
    </div>

    <% if user_signed_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">

        <li><%= link_to('Wall', posts_path) %></li>
        <li><%= link_to('Friends', friends_path) %></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('New Post', new_post_path) %></li>
            <li><%= link_to('Follow Requests', follow_requests_path) %></li>
          </ul>
        </li>
      
      </ul>
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-info">   
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
    <%end%>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_popup_frame.html.erb
<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close-popup">&times;</span>
    <div id="likers-data">
	
	</div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/alerts' %>

  <div class="container">
    <%= yield %>
  </div>
  
  <%#= debug(params) %>

  <%= render 'layouts/popup_frame' %>

  <%= yield :javascripts %>

</body>

</html>